---
- name: Install prerequisites
  apt:
    name:
      - software-properties-common
      - python3-pip
    state: present
    update_cache: yes

- name: Add Ansible PPA
  apt_repository:
    repo: ppa:ansible/ansible
    state: present
    update_cache: yes

- name: Install Ansible
  apt:
    name: ansible
    state: present
