---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Configure Nginx reverse proxy for SonarQube
  copy:
    dest: /etc/nginx/sites-available/sonarqube.conf
    content: |
      server {
          listen 80;
          server_name {{ domain_name }};

          location / {
              proxy_pass http://localhost:9000;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
              proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header X-Forwarded-Proto $scheme;
          }
      }

- name: Enable SonarQube site
  file:
    src: /etc/nginx/sites-available/sonarqube.conf
    dest: /etc/nginx/sites-enabled/sonarqube.conf
    state: link

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Test Nginx configuration
  command: nginx -t

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
